export const AUTH_USER_ID = 'chidiorji'
export const SET_AUTH_USER = 'SET_AUTH_USER'

export const RECEIVE_QUESTIONS = 'RECEIVE_QUESTIONS'
export const ANSWER_QUESTION = 'ANSWER_QUESTION'
export const ADD_POLL = 'ADD_POLL'

export const RECEIVE_USERS = 'RECEIVE_USERS'
export const UPDATE_USER_ANSWERS = 'UPDATE_USER_ANSWERS'
export const UPDATE_USER_QUESTIONS = 'UPDATE_USER_QUESTIONS'
export const LOGOUT = 'LOGOUT'
export const LOGIN = 'LOGIN'
